### PR TITLE
Fixed conflict with other plugins that use filter 'wp_edit_nav_menu_w…

### PR DESCRIPTION
**Pull request by JordanNorris**
…alker' e.g. Advanced Custom Fields, which prevent the menu editor fields from being outputted.

### CODE REVIEW

**Comment by DianaKoenraadt** [comment]
Hi Jordan,

as you can see I haven't gotten around to updating the plugin in a long, long time. I have decided to officially drop support on the plugin. (https://wordpress.org/support/topic/development-discontinued-2/)

Should you be interested in maintaining it and bringing out new releases, let me know. I'll gladly add someone to the DEV team.

Kind regards,
Diana

**Comment by JordanNorris** [comment]
Hi Diana,

Yes I would be happy to maintain the plugin. Feel free to add me to the dev team!

Best wishes,
Jordan

**Comment by DianaKoenraadt** [comment]
Hi Jordan,

great! As far as I know, WordPress only supports svn. I can add you there, so that you have access.
What is your wordpress.org username?

Kind regards,
Diana

**Comment by DianaKoenraadt** [comment]
Hey,

I can't add you. WordPress.org can't find that user.
Note: WordPress.com != WordPress.org

Kind regards,
Diana

**Pull request merged**
